### ISSUE TITLE
basic/kafka-example: PartitionNotFoundException

### ISSUE THREAD

**Issue by andregmoeller** [spring-projects/spring-integration-samples#161]
I tried out the [basic/kafka](https://github.com/spring-projects/spring-integration-samples/tree/master/basic/kafka) example and got a PartitionNotFoundException:
```
16:49:05.695 [main] ERROR o.s.boot.SpringApplication - Application startup failed
org.springframework.context.ApplicationContextException: Failed to start bean 'adapter'; nested exception is org.springframework.integration.kafka.core.PartitionNotFoundException: Partition [si.topicabc2355631326,0] has no leader or has not been found
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:176) ~[spring-context-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:51) ~[spring-context-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:346) ~[spring-context-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:149) ~[spring-context-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:112) ~[spring-context-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:851) ~[spring-context-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:540) ~[spring-context-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752) ~[spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:347) ~[spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:295) ~[spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.inon.samples.kafka.Application.main(Application.java:85) [main/:na]
Caused by: org.springframework.integration.kafka.core.PartitionNotFoundException: Partition [si.topicabc2355631326,0] has no leader or has not been found
	at org.springframework.integration.kafka.core.DefaultConnectionFactory.getLeader(DefaultConnectionFactory.java:124) ~[spring-integration-kafka-1.3.0.RELEASE.jar:na]
	at org.springframework.integration.kafka.listener.AbstractOffsetManager.getOffset(AbstractOffsetManager.java:131) ~[spring-integration-kafka-1.3.0.RELEASE.jar:na]
	at org.springframework.integration.kafka.listener.KafkaMessageListenerContainer$GetOffsetForPartitionFunction.safeValueOf(KafkaMessageListenerContainer.java:599) ~[spring-integration-kafka-1.3.0.RELEASE.jar:na]
	at org.springframework.integration.kafka.listener.KafkaMessageListenerContainer$GetOffsetForPartitionFunction.safeValueOf(KafkaMessageListenerContainer.java:593) ~[spring-integration-kafka-1.3.0.RELEASE.jar:na]
	at com.gs.collections.impl.block.function.checked.CheckedFunction.valueOf(CheckedFunction.java:30) ~[gs-collections-5.0.0.jar:na]
	at com.gs.collections.impl.block.procedure.MapCollectProcedure.value(MapCollectProcedure.java:51) ~[gs-collections-5.0.0.jar:na]
	at com.gs.collections.impl.list.immutable.ImmutableSingletonList.forEach(ImmutableSingletonList.java:59) ~[gs-collections-5.0.0.jar:na]
	at com.gs.collections.impl.utility.Iterate.forEach(Iterate.java:114) ~[gs-collections-5.0.0.jar:na]
	at com.gs.collections.impl.map.mutable.UnifiedMap.collectKeysAndValues(UnifiedMap.java:987) ~[gs-collections-5.0.0.jar:na]
	at com.gs.collections.impl.AbstractRichIterable.toMap(AbstractRichIterable.java:196) ~[gs-collections-5.0.0.jar:na]
	at org.springframework.integration.kafka.listener.KafkaMessageListenerContainer.start(KafkaMessageListenerContainer.java:312) ~[spring-integration-kafka-1.3.0.RELEASE.jar:na]
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter.doStart(KafkaMessageDrivenChannelAdapter.java:137) ~[spring-integratka-1.3.0.RELEASE.jar:na]
	at org.springframework.integration.endpoint.AbstractEndpoint.start(AbstractEndpoint.java:94) ~[spring-integration-core-4.2.2.RELEASE.jar:na]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:173) ~[spring-context-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	... 11 common frames omitted
```

I think that the problem is that [TopicCreator.start()](https://github.com/spring-projects/spring-integration-samples/blob/master/basic/kafka/src/main/java/org/springframework/integration/samples/kafka/Application.java#L187-L196) is getting called too late. I'm a beginner when it comes to Spring, but I think that TopicCreator should implement InitializingBean instead of SmartLifecycle. I made the respective change on a branch (see [Application.java](https://github.com/andregmoeller/spring-integration-samples/blob/fix-kafka-partition-not-found-exception/basic/kafka/src/main/java/org/springframework/integration/samples/kafka/Application.java#L174-L194)). It seems to work (I changed the value of kafka.topic several times and I didn't get any exceptions), but this might be pure luck.

**Comment by artembilan** [comment]
Hello @andregmoeller !

Please, share your environments and the info how you run the project.

We use the `SmartLifecycle` because `InitializingBean` is so critical to get access to the low level resources or external service.
It's typical anti-pattern do what you suggest during initialization phase.

Although I still agree that `AdminUtils.createTopic()` is still something like *init* step, but I insist that we should not do that during `afterPropertiesSet()`.

This is just sample and I and you really can live with your fix there. I'm sure in the real application your topic is supplied on the Kafka before your start the application. At least it should be like that...

**Comment by andregmoeller** [comment]
Hey Artem,

thank you for your super fast feedback! 

I start the example by entering ``./gradlew :kafka:run``. 
My machine is running Mac OS X 10.11.3. I downloaded kafka_2.11-0.8.2.2.zip and start Zookeeper by entering ``bin/zookeeper-server-start.sh config/zookeeper.properties &`` and start Kafka by entering ``bin/kafka-server-start.sh config/server.properties &``.

zookeeper.properties:
```
dataDir=/tmp/zookeeper
# the port at which the clients will connect
clientPort=2181
# disable the per-ip limit on the number of connections since this is a non-production config
maxClientCnxns=0
```

server.properties:
```
broker.id=0
port=9092
num.network.threads=3
num.io.threads=8
socket.send.buffer.bytes=102400
socket.receive.buffer.bytes=102400
socket.request.max.bytes=104857600
log.dirs=~/Documents/kafka/kafka-log-1s
num.partitions=1
num.recovery.threads.per.data.dir=1
log.retention.hours=168
log.segment.bytes=1073741824
log.retention.check.interval.ms=300000
log.cleaner.enable=false
zookeeper.connect=localhost:2181
zookeeper.connection.timeout.ms=6000
```

After reading your comment, I feel that maybe the best solution might be to 
remove ``TopicCreator`` and add a section on how to create a Kafka topic using ``kafka-topics.sh`` in the readme file.

**Comment by artembilan** [comment]
When I switch on DEBUG for the `org.springframework` category I can see something like in logs:
```
12:24:03.635 [main] INFO  o.s.c.s.DefaultLifecycleProcessor - Starting beans in phase -2147483648
12:24:03.636 [main] DEBUG o.s.c.s.DefaultLifecycleProcessor - Starting bean 'topicCreator' of type [class org.springframework.integration.samples.kafka.Application$TopicCreator]
12:24:03.636 [main] INFO  org.apache.zookeeper.ZooKeeper - Initiating client connection, connectString=localhost:2181 sessionTimeout=10000 watcher=org.I0Itec.zkclient.ZkClient@1bd0b0e5
12:24:03.637 [main-SendThread(genuine.microsoft.com:2181)] INFO  org.apache.zookeeper.ClientCnxn - Opening socket connection to server genuine.microsoft.com/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
12:24:03.638 [main-SendThread(genuine.microsoft.com:2181)] INFO  org.apache.zookeeper.ClientCnxn - Socket connection established to genuine.microsoft.com/127.0.0.1:2181, initiating session
12:24:03.638 [main-SendThread(genuine.microsoft.com:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Session establishment request sent on genuine.microsoft.com/127.0.0.1:2181
12:24:03.655 [main-SendThread(genuine.microsoft.com:2181)] INFO  org.apache.zookeeper.ClientCnxn - Session establishment complete on server genuine.microsoft.com/127.0.0.1:2181, sessionid = 0x152f04007560009, negotiated timeout = 10000
12:24:03.657 [main-SendThread(genuine.microsoft.com:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x152f04007560009, packet:: clientPath:null serverPath:null finished:false header:: 1,8  replyHeader:: 1,89,0  request:: '/brokers/ids,F  response:: v{'0} 
12:24:03.658 [main-SendThread(genuine.microsoft.com:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x152f04007560009, packet:: clientPath:null serverPath:null finished:false header:: 2,3  replyHeader:: 2,89,0  request:: '/brokers/topics/si.topic,F  response:: s{36,36,1450902406582,1450902406582,0,1,0,0,36,1,39} 
12:24:03.659 [main] DEBUG o.s.c.s.DefaultLifecycleProcessor - Successfully started bean 'topicCreator'
12:24:03.659 [main] DEBUG o.s.c.s.DefaultLifecycleProcessor - Starting bean 'application.handler.serviceActivator' of type [class org.springframework.integration.endpoint.EventDrivenConsumer]
12:24:03.659 [main] INFO  o.s.i.endpoint.EventDrivenConsumer - Adding {message-handler:application.handler.serviceActivator} as a subscriber to the 'toKafka' channel
12:24:03.659 [main] INFO  o.s.i.channel.DirectChannel - Channel 'application.toKafka' has 1 subscriber(s).
12:24:03.659 [main] INFO  o.s.i.endpoint.EventDrivenConsumer - started application.handler.serviceActivator
12:24:03.659 [main] DEBUG o.s.c.s.DefaultLifecycleProcessor - Successfully started bean 'application.handler.serviceActivator'
12:24:03.659 [main] INFO  o.s.c.s.DefaultLifecycleProcessor - Starting beans in phase 0
12:24:03.659 [main] DEBUG o.s.c.s.DefaultLifecycleProcessor - Starting bean 'producerContext' of type [class org.springframework.integration.kafka.support.KafkaProducerContext]
12:24:03.659 [main] DEBUG o.s.c.s.DefaultLifecycleProcessor - Successfully started bean 'producerContext'
12:24:03.659 [main] DEBUG o.s.c.s.DefaultLifecycleProcessor - Starting bean '_org.springframework.integration.errorLogger' of type [class org.springframework.integration.config.ConsumerEndpointFactoryBean]
12:24:03.659 [main] INFO  o.s.i.endpoint.EventDrivenConsumer - Adding {logging-channel-adapter:_org.springframework.integration.errorLogger} as a subscriber to the 'errorChannel' channel
12:24:03.659 [main] INFO  o.s.i.c.PublishSubscribeChannel - Channel 'application.errorChannel' has 1 subscriber(s).
12:24:03.659 [main] INFO  o.s.i.endpoint.EventDrivenConsumer - started _org.springframework.integration.errorLogger
12:24:03.659 [main] DEBUG o.s.c.s.DefaultLifecycleProcessor - Successfully started bean '_org.springframework.integration.errorLogger'
12:24:03.659 [main] INFO  o.s.c.s.DefaultLifecycleProcessor - Starting beans in phase 1073741823
12:24:03.659 [main] DEBUG o.s.c.s.DefaultLifecycleProcessor - Starting bean 'adapter' of type [class org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter]
12:24:03.721 [main] INFO  o.s.i.k.i.KafkaMessageDrivenChannelAdapter - started adapter
12:24:03.721 [main] DEBUG o.s.c.s.DefaultLifecycleProcessor - Successfully started bean 'adapter'
```

So, as you see the `TopicCreator` starts enough early before the last one `KafkaMessageDrivenChannelAdapter`, like we see in your StackTrace:
```
 at org.springframework.integration.kafka.listener.KafkaMessageListenerContainer.start(KafkaMessageListenerContainer.java:312) ~[spring-integration-kafka-1.3.0.RELEASE.jar:na]
    at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter.doStart(KafkaMessageDrivenChannelAdapter.java:137) ~[spring-integratka-1.3.0.RELEASE.jar:na]
```

So, I assume the only problem that we exit from the `AdminUtils.createTopic()` very early, because it might be *aync*. Therefore the `KafkaMessageDrivenChannelAdapter` gets the control to start from its phase. 

Looks like we should take a look into utilization our own function - `TopicUtils.ensureTopicCreated()`.

**Comment by artembilan** [comment]
Please, try this in the `TopicCreator`:
```
		@Override
		public void start() {
			TopicUtils.ensureTopicCreated(this.zkConnect, this.topic, 1, 1);
			this.running = true;
		}

```

**Comment by andregmoeller** [comment]
Thanks a lot! This fixes the problem!

**Comment by artembilan** [comment]
Great! 
We can push that to the main repo.
