### ISSUE TITLE
Cannot resolve the name 'integration:smartLifeCycleAttributeGroup' to a(n) 'attribute group' component when packaged with Maven

### ISSUE THREAD

**Issue by dilzfiesta** [spring-projects/spring-integration-samples#168]
**When i try to package using maven, some test fails as show below -**
```
Gyro:tcp-client-server gyro$ mvn clean package
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.springframework.integration.samples:tcp-client-server:jar:4.3.0.BUILD-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ line 129, column 12
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-shade-plugin is missing. @ line 114, column 12
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building TCP Client Server Sample 4.3.0.BUILD-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ tcp-client-server ---
[INFO] Deleting /Users/gyro/Documents/workspace-sts-3.7.3.RELEASE/spring-integration-samples/basic/tcp-client-server/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ tcp-client-server ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 5 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ tcp-client-server ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 6 source files to /Users/gyro/Documents/workspace-sts-3.7.3.RELEASE/spring-integration-samples/basic/tcp-client-server/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ tcp-client-server ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/gyro/Documents/workspace-sts-3.7.3.RELEASE/spring-integration-samples/basic/tcp-client-server/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ tcp-client-server ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 6 source files to /Users/gyro/Documents/workspace-sts-3.7.3.RELEASE/spring-integration-samples/basic/tcp-client-server/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ tcp-client-server ---
[INFO] Surefire report directory: /Users/gyro/Documents/workspace-sts-3.7.3.RELEASE/spring-integration-samples/basic/tcp-client-server/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.springframework.integration.samples.tcpclientserver.TcpClientServerAnnotationDemoTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.883 sec
Running org.springframework.integration.samples.tcpclientserver.TcpClientServerDemoTest
16:43:26.915 INFO  [main][org.springframework.integration.samples.tcpclientserver.support.CustomTestContextLoader] Available server socket: 5678
16:43:27.930 ERROR [pool-3-thread-2][org.springframework.integration.handler.LoggingHandler] org.springframework.messaging.MessageHandlingException: nested exception is java.lang.RuntimeException: Failure Demonstration
	at org.springframework.integration.handler.MethodInvokingMessageProcessor.processMessage(MethodInvokingMessageProcessor.java:96)
	at org.springframework.integration.handler.ServiceActivatingHandler.handleRequestMessage(ServiceActivatingHandler.java:89)
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:99)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:127)
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:116)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:147)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:120)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:77)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:423)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:373)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:115)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:45)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:105)
	at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutput(AbstractMessageProducingHandler.java:297)
	at org.springframework.integration.handler.AbstractMessageProducingHandler.produceOutput(AbstractMessageProducingHandler.java:217)
	at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutputs(AbstractMessageProducingHandler.java:119)
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:105)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:127)
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:116)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:147)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:120)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:77)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:423)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:115)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSendAndReceive(GenericMessagingTemplate.java:150)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSendAndReceive(GenericMessagingTemplate.java:45)
	at org.springframework.messaging.core.AbstractMessagingTemplate.sendAndReceive(AbstractMessagingTemplate.java:42)
	at org.springframework.integration.core.MessagingTemplate.sendAndReceive(MessagingTemplate.java:97)
	at org.springframework.integration.gateway.MessagingGatewaySupport.doSendAndReceive(MessagingGatewaySupport.java:422)
	at org.springframework.integration.gateway.MessagingGatewaySupport.sendAndReceiveMessage(MessagingGatewaySupport.java:390)
	at org.springframework.integration.ip.tcp.TcpInboundGateway.doOnMessage(TcpInboundGateway.java:119)
	at org.springframework.integration.ip.tcp.TcpInboundGateway.onMessage(TcpInboundGateway.java:97)
	at org.springframework.integration.ip.tcp.connection.TcpNetConnection.run(TcpNetConnection.java:182)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Failure Demonstration
	at org.springframework.integration.samples.tcpclientserver.EchoService.test(EchoService.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springframework.expression.spel.support.ReflectiveMethodExecutor.execute(ReflectiveMethodExecutor.java:113)
	at org.springframework.expression.spel.ast.MethodReference.getValueInternal(MethodReference.java:129)
	at org.springframework.expression.spel.ast.MethodReference.access$000(MethodReference.java:49)
	at org.springframework.expression.spel.ast.MethodReference$MethodValueRef.getValue(MethodReference.java:347)
	at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:88)
	at org.springframework.expression.spel.ast.SpelNodeImpl.getTypedValue(SpelNodeImpl.java:131)
	at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:330)
	at org.springframework.integration.util.AbstractExpressionEvaluator.evaluateExpression(AbstractExpressionEvaluator.java:166)
	at org.springframework.integration.util.MessagingMethodInvokerHelper.processInternal(MessagingMethodInvokerHelper.java:317)
	at org.springframework.integration.util.MessagingMethodInvokerHelper.process(MessagingMethodInvokerHelper.java:155)
	at org.springframework.integration.handler.MethodInvokingMessageProcessor.processMessage(MethodInvokingMessageProcessor.java:93)
	... 35 more

FAIL:Failure Demonstration
echo:Hello world!
echo:
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.13 sec
Running org.springframework.integration.samples.tcpclientserver.TcpClientServerDemoWithConversionServiceTest
16:43:28.050 INFO  [main][org.springframework.integration.samples.tcpclientserver.support.CustomTestContextLoader] Available server socket: 5678
16:43:28.559 ERROR [pool-5-thread-2][org.springframework.integration.handler.LoggingHandler] org.springframework.messaging.MessageHandlingException: nested exception is java.lang.RuntimeException: Failure Demonstration
	at org.springframework.integration.handler.MethodInvokingMessageProcessor.processMessage(MethodInvokingMessageProcessor.java:96)
	at org.springframework.integration.handler.ServiceActivatingHandler.handleRequestMessage(ServiceActivatingHandler.java:89)
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:99)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:127)
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:116)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:147)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:120)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:77)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:423)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:115)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSendAndReceive(GenericMessagingTemplate.java:150)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSendAndReceive(GenericMessagingTemplate.java:45)
	at org.springframework.messaging.core.AbstractMessagingTemplate.sendAndReceive(AbstractMessagingTemplate.java:42)
	at org.springframework.integration.core.MessagingTemplate.sendAndReceive(MessagingTemplate.java:97)
	at org.springframework.integration.gateway.MessagingGatewaySupport.doSendAndReceive(MessagingGatewaySupport.java:422)
	at org.springframework.integration.gateway.MessagingGatewaySupport.sendAndReceiveMessage(MessagingGatewaySupport.java:390)
	at org.springframework.integration.ip.tcp.TcpInboundGateway.doOnMessage(TcpInboundGateway.java:119)
	at org.springframework.integration.ip.tcp.TcpInboundGateway.onMessage(TcpInboundGateway.java:97)
	at org.springframework.integration.ip.tcp.connection.TcpNetConnection.run(TcpNetConnection.java:182)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Failure Demonstration
	at org.springframework.integration.samples.tcpclientserver.EchoService.test(EchoService.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springframework.expression.spel.support.ReflectiveMethodExecutor.execute(ReflectiveMethodExecutor.java:113)
	at org.springframework.expression.spel.ast.MethodReference.getValueInternal(MethodReference.java:129)
	at org.springframework.expression.spel.ast.MethodReference.access$000(MethodReference.java:49)
	at org.springframework.expression.spel.ast.MethodReference$MethodValueRef.getValue(MethodReference.java:347)
	at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:88)
	at org.springframework.expression.spel.ast.SpelNodeImpl.getTypedValue(SpelNodeImpl.java:131)
	at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:330)
	at org.springframework.integration.util.AbstractExpressionEvaluator.evaluateExpression(AbstractExpressionEvaluator.java:166)
	at org.springframework.integration.util.MessagingMethodInvokerHelper.processInternal(MessagingMethodInvokerHelper.java:317)
	at org.springframework.integration.util.MessagingMethodInvokerHelper.process(MessagingMethodInvokerHelper.java:155)
	at org.springframework.integration.handler.MethodInvokingMessageProcessor.processMessage(MethodInvokingMessageProcessor.java:93)
	... 21 more

FAIL:Failure Demonstration
echo:Hello world!
echo:
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.576 sec
Running org.springframework.integration.samples.tcpclientserver.TcpServerConnectionDeserializeTest
16:43:28.632 INFO  [main][org.springframework.integration.samples.tcpclientserver.support.CustomTestContextLoader] Available server socket: 5678
16:43:29.018 DEBUG [pool-7-thread-2][org.springframework.integration.samples.tcpclientserver.TcpServerConnectionDeserializeTest$1] org.springframework.integration.samples.tcpclientserver.TcpServerConnectionDeserializeTest$1@9023440 received message: GenericMessage [payload=byte[12], headers={replyChannel=org.springframework.messaging.core.GenericMessagingTemplate$TemporaryReplyChannel@7c5cb10, errorChannel=org.springframework.messaging.core.GenericMessagingTemplate$TemporaryReplyChannel@7c5cb10, ip_tcp_remotePort=50429, ip_connectionId=localhost:50429:5678:7c51dc3f-7867-4278-8912-9daf38ca4732, ip_localInetAddress=/127.0.0.1, ip_address=127.0.0.1, id=57021dbd-bc36-b294-8164-0ac6d5fcd265, ip_hostname=localhost, timestamp=1462286609017}]
16:43:29.019 ERROR [pool-7-thread-2][org.springframework.integration.ip.tcp.connection.TcpNetConnection] Read exception localhost:50429:5678:7c51dc3f-7867-4278-8912-9daf38ca4732 MessageMappingException:Expected STX to begin message
Hello World!
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.405 sec
Running org.springframework.integration.samples.tcpclientserver.TcpServerCustomSerializerTest
16:43:29.067 INFO  [main][org.springframework.integration.samples.tcpclientserver.support.CustomTestContextLoader] Available server socket: 5678
16:43:29.399 DEBUG [pool-9-thread-2][org.springframework.integration.samples.tcpclientserver.TcpServerCustomSerializerTest$1] org.springframework.integration.samples.tcpclientserver.TcpServerCustomSerializerTest$1@4ddc4e42 received message: GenericMessage [payload=org.springframework.integration.samples.tcpclientserver.CustomOrder@473301d1[
  number=123
  sender=PINGPONG02
  message=You got it to work!
], headers={replyChannel=org.springframework.messaging.core.GenericMessagingTemplate$TemporaryReplyChannel@2985d9d5, errorChannel=org.springframework.messaging.core.GenericMessagingTemplate$TemporaryReplyChannel@2985d9d5, ip_tcp_remotePort=50430, ip_connectionId=localhost:50430:5678:e4251f9f-6ad2-486f-9400-91a2ddd7bfad, ip_localInetAddress=/127.0.0.1, ip_address=127.0.0.1, id=5ee26447-f855-4ac3-1186-8fb581715810, ip_hostname=localhost, timestamp=1462286609380}]
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.379 sec

Results :

Tests run: 9, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ tcp-client-server ---
[INFO] Building jar: /Users/gyro/Documents/workspace-sts-3.7.3.RELEASE/spring-integration-samples/basic/tcp-client-server/target/tcp-client-server-4.3.0.BUILD-SNAPSHOT.jar
[INFO] 
[INFO] --- maven-shade-plugin:2.4.3:shade (default) @ tcp-client-server ---
[INFO] Including commons-lang:commons-lang:jar:2.6 in the shaded jar.
[INFO] Including org.springframework:spring-core:jar:4.2.5.RELEASE in the shaded jar.
[INFO] Including commons-logging:commons-logging:jar:1.2 in the shaded jar.
[INFO] Including org.springframework.integration:spring-integration-ip:jar:4.3.0.M1 in the shaded jar.
[INFO] Including org.springframework.integration:spring-integration-core:jar:4.3.0.M1 in the shaded jar.
[INFO] Including org.springframework:spring-tx:jar:4.2.4.RELEASE in the shaded jar.
[INFO] Including org.springframework.retry:spring-retry:jar:1.1.2.RELEASE in the shaded jar.
[INFO] Including org.springframework:spring-aop:jar:4.2.4.RELEASE in the shaded jar.
[INFO] Including aopalliance:aopalliance:jar:1.0 in the shaded jar.
[INFO] Including log4j:log4j:jar:1.2.17 in the shaded jar.
[INFO] Including org.springframework.integration:spring-integration-test:jar:4.3.0.M1 in the shaded jar.
[INFO] Including org.springframework:spring-context:jar:4.2.4.RELEASE in the shaded jar.
[INFO] Including org.springframework:spring-beans:jar:4.2.4.RELEASE in the shaded jar.
[INFO] Including org.springframework:spring-expression:jar:4.2.4.RELEASE in the shaded jar.
[INFO] Including org.springframework:spring-messaging:jar:4.2.4.RELEASE in the shaded jar.
[INFO] Replacing /Users/gyro/Documents/workspace-sts-3.7.3.RELEASE/spring-integration-samples/basic/tcp-client-server/target/uber-tcp-client-server-4.3.0.BUILD-SNAPSHOT.jar with /Users/gyro/Documents/workspace-sts-3.7.3.RELEASE/spring-integration-samples/basic/tcp-client-server/target/tcp-client-server-4.3.0.BUILD-SNAPSHOT-shaded.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.983 s
[INFO] Finished at: 2016-05-03T16:43:33+02:00
[INFO] Final Memory: 25M/165M
[INFO] ------------------------------------------------------------------------
```

**And when i try to run the generated jar, I get the below error -**
```
Gyro:tcp-client-server gyro$ java -jar target/uber-tcp-client-server-4.3.0.BUILD-SNAPSHOT.jar 

=========================================================
                                                         
    Welcome to the Spring Integration                    
          TCP-Client-Server Sample!                      
                                                         
    For more information please visit:                   
    http://www.springintegration.org/                    
                                                         
=========================================================
Detect open server socket...using port 5678
Exception in thread "main" org.springframework.beans.factory.xml.XmlBeanDefinitionStoreException: Line 55 in XML document from class path resource [META-INF/spring/integration/tcpClientServerDemo-context.xml] is invalid; nested exception is org.xml.sax.SAXParseException; systemId: http://www.springframework.org/schema/integration/ip/spring-integration-ip.xsd; lineNumber: 55; columnNumber: 75; src-resolve: Cannot resolve the name 'integration:smartLifeCycleAttributeGroup' to a(n) 'attribute group' component.
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:399)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:336)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:304)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:181)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:217)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:188)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:252)
	at org.springframework.context.support.GenericXmlApplicationContext.load(GenericXmlApplicationContext.java:124)
	at org.springframework.integration.samples.tcpclientserver.Main.setupContext(Main.java:125)
	at org.springframework.integration.samples.tcpclientserver.Main.main(Main.java:75)
Caused by: org.xml.sax.SAXParseException; systemId: http://www.springframework.org/schema/integration/ip/spring-integration-ip.xsd; lineNumber: 55; columnNumber: 75; src-resolve: Cannot resolve the name 'integration:smartLifeCycleAttributeGroup' to a(n) 'attribute group' component.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:437)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaErr(XSDHandler.java:4162)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaError(XSDHandler.java:4145)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getGlobalDecl(XSDHandler.java:1741)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDAttributeGroupTraverser.traverseLocal(XSDAttributeGroupTraverser.java:80)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDAbstractTraverser.traverseAttrsAndAttrGrps(XSDAbstractTraverser.java:643)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDComplexTypeTraverser.processComplexContent(XSDComplexTypeTraverser.java:1123)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDComplexTypeTraverser.traverseComplexContent(XSDComplexTypeTraverser.java:836)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDComplexTypeTraverser.traverseComplexTypeDecl(XSDComplexTypeTraverser.java:315)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDComplexTypeTraverser.traverseLocal(XSDComplexTypeTraverser.java:164)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDElementTraverser.traverseNamedElement(XSDElementTraverser.java:392)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDElementTraverser.traverseGlobal(XSDElementTraverser.java:242)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.traverseSchemas(XSDHandler.java:1433)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.parseSchema(XSDHandler.java:630)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadSchema(XMLSchemaLoader.java:617)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.findSchemaGrammar(XMLSchemaValidator.java:2453)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:1773)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.emptyElement(XMLSchemaValidator.java:766)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:356)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2786)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:348)
	at org.springframework.beans.factory.xml.DefaultDocumentLoader.loadDocument(DefaultDocumentLoader.java:76)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadDocument(XmlBeanDefinitionReader.java:429)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:391)
	... 9 more
```
**I have added below in pom.xml -**

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-shade-plugin</artifactId>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>shade</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<finalName>uber-${project.artifactId}-${project.version}</finalName>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<configuration>
					<archive>
						<manifest>
							<mainClass>org.springframework.integration.samples.tcpclientserver.Main</mainClass>
						</manifest>
					</archive>
				</configuration>
			</plugin>
		</plugins>
	</build>

**My maven version -**
```
Gyro:tcp-client-server gyro$ mvn --version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: /usr/local/apache-maven-3.3.9
Java version: 1.8.0_31, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.4", arch: "x86_64", family: "mac"
```

**Comment by artembilan** [comment]
> some test fails as show below

That's not true by your maven report:
```
Results :
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0
...
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.983 s
```
What you see there in log are `intentional` exceptions do demonstrate the error handling process. And you even can see there `Failure Demonstration` words.

Investigating everything rest...

But, please, study the [GitHub Commenting](https://help.github.com/categories/writing-on-github/) for the future to simplify readers life.

**Comment by dilzfiesta** [comment]
My bad, thanks for pointing it out !

Although the generated uber jar did failed with the below exception, can you please help me with that.

`Exception in thread "main" org.springframework.beans.factory.xml.XmlBeanDefinitionStoreException: Line 55 in XML document from class path resource [META-INF/spring/integration/tcpClientServerDemo-context.xml] is invalid; nested exception is org.xml.sax.SAXParseException; systemId: http://www.springframework.org/schema/integration/ip/spring-integration-ip.xsd; lineNumber: 55; columnNumber: 75; src-resolve: Cannot resolve the name 'integration:smartLifeCycleAttributeGroup' to a(n) 'attribute group' component.`

Thanks.

**Comment by artembilan** [comment]
M-m-m. Not sure how `maven-shade-plugin` works, but you should be sure that you run the proper `jar`.
Which really is `uber` and includes `spring-integration-core` artifact. 
Right now we see that it is a case since we don't see XSD in classpath.

Maybe you really should use the original jar like it sounds in logs:
```
[INFO] Replacing /Users/gyro/Documents/workspace-sts-3.7.3.RELEASE/spring-integration-samples/basic/tcp-client-server/target/uber-tcp-client-server-4.3.0.BUILD-SNAPSHOT.jar with /Users/gyro/Documents/workspace-sts-3.7.3.RELEASE/spring-integration-samples/basic/tcp-client-server/target/tcp-client-server-4.3.0.BUILD-SNAPSHOT-shaded.jar
[INFO] ------------------------------------------------------------------------
```
?

Note: since it's not an issue of the project, but some your customization, you should ask similar questions on the StackOverflow (`spring-integration` tag) first of all.

**Comment by dilzfiesta** [comment]
`maven-share-plugin` automatically includes all the dependencies while generating the jar. If not included, below error popups up while packaging and running.
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/springframework/core/env/PropertySource
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2693)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3040)
	at java.lang.Class.getMethod0(Class.java:3010)
	at java.lang.Class.getMethod(Class.java:1776)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: org.springframework.core.env.PropertySource
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
```
I will double check and try to post this question on StackOverflow.
Thanks.
