### ISSUE TITLE
java.lang.NoSuchMethodError: com.sun.mail.imap.IMAPFolder.idle()

### ISSUE THREAD

**Issue by pankajkh** [spring-projects/spring-integration-samples#197]
Hi,

We are getting NoSuchMethodError. Here are the stack trace.

18/Feb/2017:07:48:13.155 [pool-4-thread-1]  ERROR o.s.s.s.TaskUtils$LoggingErrorHandler.handleError(95) - Unexpected error occurred in scheduled task.
java.lang.NoSuchMethodError: com.sun.mail.imap.IMAPFolder.idle()V
        at org.springframework.integration.mail.ImapMailReceiver.waitForNewMessages(ImapMailReceiver.java:175) ~[spring-integration-mail-4.3.1.RELEASE.jar:4.3.1.RELEASE]
        at org.springframework.integration.mail.ImapIdleChannelAdapter$IdleTask.run(ImapIdleChannelAdapter.java:271) ~[spring-integration-mail-4.3.1.RELEASE.jar:4.3.1.RELEASE]
        at org.springframework.integration.mail.ImapIdleChannelAdapter$ReceivingTask.run(ImapIdleChannelAdapter.java:241) ~[spring-integration-mail-4.3.1.RELEASE.jar:4.3.1.RELEASE]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_101]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_101]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_101]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_101]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]
18/Feb/2017:07:48:14.172 [pool-7-thread-1]  ERROR o.s.s.s.TaskUtils$LoggingErrorHandler.handleError(95) - Unexpected error occurred in scheduled task.
java.lang.NoSuchMethodError: com.sun.mail.imap.IMAPFolder.idle()V
        at org.springframework.integration.mail.ImapMailReceiver.waitForNewMessages(ImapMailReceiver.java:175) ~[spring-integration-mail-4.3.1.RELEASE.jar:4.3.1.RELEASE]
        at org.springframework.integration.mail.ImapIdleChannelAdapter$IdleTask.run(ImapIdleChannelAdapter.java:271) ~[spring-integration-mail-4.3.1.RELEASE.jar:4.3.1.RELEASE]
        at org.springframework.integration.mail.ImapIdleChannelAdapter$ReceivingTask.run(ImapIdleChannelAdapter.java:241) ~[spring-integration-mail-4.3.1.RELEASE.jar:4.3.1.RELEASE]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.0.RELEASE.jar:4.2.0.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_101]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_101]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_101]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_101]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]

Here the spring configuration : 

<int:service-activator input-channel="emailReceiveChannel" ref="emailReceiver" method="emailReceived" />
    <int:channel id="emailReceiveChannel" />

    <int-mail:imap-idle-channel-adapter id="customAdapter"
        store-uri="${lab.mail.store-uri}"
        channel="emailReceiveChannel"
        auto-startup="${lab.mail.autostart}"
        should-delete-messages="false"
        should-mark-messages-as-read="true"
        java-mail-properties="javaMailProperties"/>

    <util:properties id="javaMailProperties">
        <prop key="mail.imap.socketFactory.class">javax.net.ssl.SSLSocketFactory</prop>
        <prop key="mail.imap.socketFactory.fallback">false</prop>
        <prop key="mail.store.protocol">imaps</prop>
        <prop key="mail.debug">false</prop>
    </util:properties>

It is flooding our log files. Please help how to fix it.

Thanks,
Pankaj

**Comment by garyrussell** [comment]
You seem to have an old version of `com.sun.mail:imap` on your classpath - try using a more recent version (e.g. 1.5.6).

**Comment by rohangulati** [comment]
This also happens when you are using `javax.mail` standalone with `spring-boot-starter-mail`. `com.sun.mail:imap` uses `javax.mail`(v.1.5.6) internally. When you are using `javax.mail` version other than `1.5.6`, you have 2 version of the `IMAPFolder` (one from `com.sun.mail` and other from `javax.mail`) in your dependency tree. Maven will resolve this conflict by choosing `IMAPFolder` from `javax.mail` which does not contain the`idle()` method. This causes the `java.lang.NoSuchMethodError` exception.
<br/>
**Solution**
You can update the version of `javax.mail` to `1.5.6` to make it compliant with `com.sun.mail:imap`

**Comment by pankajkh** [comment]
Hi Rohan,
Yes, we are using javax.mail standalone. https://mvnrepository.com/artifact/javax.mail/mail/1.4.7 
Should I replace it with https://mvnrepository.com/artifact/com.sun.mail/javax.mail/1.5.6  ?

Thanks,
Pankaj

**Comment by artembilan** [comment]
No, replacement. You should declare like:
```
compile "javax.mail:javax.mail-api:1.5.6"
compile "com.sun.mail:javax.mail:1.5.6"
compile "com.sun.mail:imap:1.5.6"
```

**Comment by rohangulati** [comment]
@pankajkh I had the same issue, so updating the version of `javax.mail` to `1.5.6` my `pom.xml` fixed this

**Comment by pankajkh** [comment]
@artembilan  : Can you please provide more detail ? How it will fix the issue.
@rohangulati  : there is no version 1.5.6 to upgrade for jar (javax.mail:mail). I need to replace with other jar (com.sun.mail:javax.mail).

**Comment by rohangulati** [comment]
@pankajkh You should use https://mvnrepository.com/artifact/javax.mail/javax.mail-api/1.5.6

**Comment by artembilan** [comment]
One more time:
```
javax.mail:javax.mail-api:1.5.6
```
not
```
javax.mail:javax.mail:1.5.6
```
The impl is in the `com.sun.mail:javax.mail:1.5.6`.

**Comment by pankajkh** [comment]
Thanks a lot, got it now.

**Comment by garyrussell** [comment]
You must still have an incompatible imap jar on the class path somehow. Run the jvm with `-verbose` to see which jar `IMAPFolder` is being loaded from.

**Comment by venkatr123** [comment]
IMAPFolder  class is only  there in  javax.mail:javax.mail:1.5.6
not in  javax.mail:javax.mail-api:1.5.6

in run time it's not picking the idle()  it's there in IMAPFolder

**Comment by venkatr123** [comment]
i am running this application as standalone by using this jar https://mvnrepository.com/artifact/javax.mail/javax.mail/1.6.0  this not web app

**Comment by garyrussell** [comment]
What version of Spring Integration? 5.1.2 uses javamail 1.6.2 and works fine.

Show your complete POM.

**Comment by venkatr123** [comment]
this is spring version
	<spring.version>4.3.8.RELEASE</spring.version>

**Comment by garyrussell** [comment]
I asked for spring-integration version.

**Comment by venkatr123** [comment]
means  i did't get you

**Comment by garyrussell** [comment]
This is becoming tedious; as I said

>Show your complete POM.

**Comment by venkatr123** [comment]
we are not using spring integaration

**Comment by garyrussell** [comment]
So why are you asking this question in a Spring Integration GitHub issue?
