### ISSUE TITLE
Is the FTP example, actually working?

### ISSUE THREAD

**Issue by columb1a** [spring-projects/spring-integration-samples#198]
when I run it I'm getting this:

```
org.springframework.messaging.MessagingException:` Failed to invoke handler; nested exception is org.springframework.messaging.MessagingException: Failed to execute on session; nested exception is java.lang.IllegalStateException: failed to create FTPClient, failedMessage=GenericMessage [payload=target\toSend\a.txt, headers={timestamp=1489108163505, id=84218d92-8f62-13aa-587f-3cf1e9768a5b}]
	at org.springframework.integration.handler.advice.RequestHandlerRetryAdvice.doInvoke(RequestHandlerRetryAdvice.java:100)
	at org.springframework.integration.handler.advice.AbstractRequestHandlerAdvice.invoke(AbstractRequestHandlerAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy11.handleMessage(Unknown Source)
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:116)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:148)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:121)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:89)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:423)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:373)
	at com.ftp.samples.FtpOutboundChannelAdapterSample.runDemo(FtpOutboundChannelAdapterSample.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: org.springframework.messaging.MessagingException: Failed to execute on session; nested exception is java.lang.IllegalStateException: failed to create FTPClient
	at org.springframework.integration.file.remote.RemoteFileTemplate.execute(RemoteFileTemplate.java:444)
	at org.springframework.integration.file.remote.RemoteFileTemplate.send(RemoteFileTemplate.java:283)
	at org.springframework.integration.file.remote.RemoteFileTemplate.send(RemoteFileTemplate.java:273)
	at org.springframework.integration.file.remote.RemoteFileTemplate.send(RemoteFileTemplate.java:265)
	at org.springframework.integration.file.remote.handler.FileTransferringMessageHandler.handleMessageInternal(FileTransferringMessageHandler.java:170)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:127)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.integration.handler.advice.AbstractRequestHandlerAdvice$1.cloneAndExecute(AbstractRequestHandlerAdvice.java:93)
	at org.springframework.integration.handler.advice.RequestHandlerRetryAdvice$2.doWithRetry(RequestHandlerRetryAdvice.java:93)
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:276)
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:201)
	at org.springframework.integration.handler.advice.RequestHandlerRetryAdvice.doInvoke(RequestHandlerRetryAdvice.java:89)
	... 35 more
Caused by: java.lang.IllegalStateException: failed to create FTPClient
	at org.springframework.integration.ftp.session.AbstractFtpSessionFactory.getSession(AbstractFtpSessionFactory.java:169)
	at org.springframework.integration.ftp.session.AbstractFtpSessionFactory.getSession(AbstractFtpSessionFactory.java:41)
	at org.springframework.integration.file.remote.RemoteFileTemplate.execute(RemoteFileTemplate.java:433)
	... 52 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at org.apache.commons.net.SocketClient.connect(SocketClient.java:188)
	at org.apache.commons.net.SocketClient.connect(SocketClient.java:209)
	at org.springframework.integration.ftp.session.AbstractFtpSessionFactory.createClient(AbstractFtpSessionFactory.java:192)
	at org.springframework.integration.ftp.session.AbstractFtpSessionFactory.getSession(AbstractFtpSessionFactory.java:166)
	... 54 more
```

Also, what does it means? `spring-integration-samples/basic/ftp/src/test/java/org/springframework/integration/samples/ftp/support/TestUserManager.java`

It says don't use hardcoded Port. But, how to do that?

**Comment by columb1a** [comment]
Nevermind. Was my fault.

**Comment by artembilan** [comment]
The SO question on the matter: http://stackoverflow.com/questions/42710311/ftp-example-randomly-not-working

This might be a bug, but, please, let's don't steal time of each other in different channels for the same subject.

**Comment by artembilan** [comment]
@columb1a ,

Pay attention to the PR which might fix your concern.
Indeed, we have seen a similar sporadic failure for these FTP tests not one time on our CI server...

**Comment by columb1a** [comment]
What do you mean with PR?

**Comment by artembilan** [comment]
"Pull Request": https://help.github.com/articles/about-pull-requests/

See this one: #199

**Comment by columb1a** [comment]
It didn't fix the issue 100% I'm still having the same issue as before.  What I noticed debbuging my project is, sometimes the "username" that is loaded in the FTP session factory actually is my window's username (let's say it was like "rxx", instead of the username that comes within the properties file (which is "demo").
After having hardcoded the username as a "demo", I haven't had any issues....so far.

**Comment by artembilan** [comment]
Well, but authentication problem should be fully different story then connection refused because no listener on port. Isn't it?
So, let's address it separately!

I also use Windows, so we can easily pair with you the solution.

As far as I know `username` is really system property on Windows. So, the problem might be sporadic depending of what loads first (or nay be last?) - properties file or system properties.

I suppose the easiest way is to rename the property to be sure that only ours has affect to the target application.
WDYT?

**Comment by columb1a** [comment]
man, that was the solution :). In fact I just tested the same project in my macbook using "username" as property, and everything went well (in mac). In windows I just changed the property name to username_whatever and it worked.

**Comment by artembilan** [comment]
Good.
I can utilize that into the PR to make the fix generally available, but let me know what and how have you changed?
The problem that I see `username` property in the SFTP sample, but we talk here about FTP, which has `userid`.
What am I missing?
Thanks

**Comment by columb1a** [comment]
Well, I forgot to say something. Yesterday I decied to change a little the FTP sample. So now, I'm using another strategy (and it shouldn't failed so far: 100% of build sucess so far). What I did was to load the properties related to the ftpSessionFactory as the SFTP sample is doing so (so first I load the FTP server using smartLifeCycle, and then I get the PORT that was set, and I assign that port to my FtpSessionFactory). Like this: [SFTP EXAMPLE](https://github.com/spring-projects/spring-integration-samples/blob/master/basic/sftp/src/test/resources/META-INF/spring/integration/SftpSampleCommon.xml)

**Comment by artembilan** [comment]
OK. Thank you for explanation.
Although it confuses us, but we are happy to hear that you found a solution for your use-case.
Nevertheless I see that it suffers the same `port already in use` problem do not have proper connection from the client.
I will fix the SFTP sample the same way as I'm doing in PR for FTP.
And yes, that `username` will be fixed as well to meet Windows environment.

But, please, be more specific in the future with the description of the problem.
Because right now it looks like original issues has gone and you have given birth to new ones almost unrelated to the sample.

**Comment by artembilan** [comment]
See #199 for an appropriate fix for SFTP.
