### ISSUE TITLE
Error:Failed to notify build listener.

### ISSUE THREAD

**Issue by IceFlakes** [spring-projects/spring-integration-samples#270]
Gradle refresh failed...
the idea log:

...2019-06-01 10:29:08,778 [ 211877]   WARN - nal.AbstractExternalSystemTask - Failed to notify build listener. 
com.intellij.openapi.externalSystem.model.ExternalSystemException: Failed to notify build listener.
	at org.jetbrains.plugins.gradle.service.project.AbstractProjectImportErrorHandler.createUserFriendlyError(AbstractProjectImportErrorHandler.java:107)
	at org.jetbrains.plugins.gradle.service.project.BaseProjectImportErrorHandler.getUserFriendlyError(BaseProjectImportErrorHandler.java:169)
	at org.jetbrains.plugins.gradle.service.project.BaseGradleProjectResolverExtension.getUserFriendlyError(BaseGradleProjectResolverExtension.java:645)
	at com.android.tools.idea.gradle.project.AndroidGradleProjectResolver.getUserFriendlyError(AndroidGradleProjectResolver.java:405)
	at org.jetbrains.plugins.gradle.service.project.AbstractProjectResolverExtension.getUserFriendlyError(AbstractProjectResolverExtension.java:158)
	at org.jetbrains.plugins.gradle.service.project.AbstractProjectResolverExtension.getUserFriendlyError(AbstractProjectResolverExtension.java:158)
	at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver$ProjectConnectionDataNodeFunction.fun(GradleProjectResolver.java:802)
	at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver$ProjectConnectionDataNodeFunction.fun(GradleProjectResolver.java:782)
	at org.jetbrains.plugins.gradle.service.execution.GradleExecutionHelper.execute(GradleExecutionHelper.java:217)
	at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver.resolveProjectInfo(GradleProjectResolver.java:132)
	at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver.resolveProjectInfo(GradleProjectResolver.java:72)
	at com.intellij.openapi.externalSystem.service.remote.RemoteExternalSystemProjectResolverImpl.a(RemoteExternalSystemProjectResolverImpl.java:37)
	at com.intellij.openapi.externalSystem.service.remote.AbstractRemoteExternalSystemService.execute(AbstractRemoteExternalSystemService.java:59)
	at com.intellij.openapi.externalSystem.service.remote.RemoteExternalSystemProjectResolverImpl.resolveProjectInfo(RemoteExternalSystemProjectResolverImpl.java:37)
	at com.intellij.openapi.externalSystem.service.remote.wrapper.ExternalSystemProjectResolverWrapper.resolveProjectInfo(ExternalSystemProjectResolverWrapper.java:49)
	at com.intellij.openapi.externalSystem.service.internal.ExternalSystemResolveProjectTask.doExecute(ExternalSystemResolveProjectTask.java:51)
	at com.intellij.openapi.externalSystem.service.internal.AbstractExternalSystemTask.execute(AbstractExternalSystemTask.java:139)
	at com.intellij.openapi.externalSystem.service.internal.AbstractExternalSystemTask.execute(AbstractExternalSystemTask.java:125)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$3.execute(ExternalSystemUtil.java:414)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$5.run(ExternalSystemUtil.java:495)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:710)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:309)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

2019-06-01 10:31:32,029 [ 355128]   INFO - ide.actions.ShowFilePathAction - 
Exit code 1

**Comment by artembilan** [comment]
This doesn't sound like Spring Integration related: https://spring.io/projects/spring-integration#overview
Closing as *invalid*.
Thanks for understanding.

**Comment by IceFlakes** [comment]
the error caused by gradle plugin version in idea.i got it

**Comment by IceFlakes** [comment]
the cafe-dsl moudle has a complie error in Application.caused by the model OrderItem can not cast to Drink

**Comment by artembilan** [comment]
> OrderItem can not cast to Drink

Not enough info.
Something else is going around that in your case.

Have just loaded the latest master of the project, opened that `cafe-dsl` and this is a result running it from IDEA:
``` 
 .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::  (v2.2.0.BUILD-SNAPSHOT)

Hit 'Enter' to terminate
task-scheduler-1 prepared cold drink #1 for order #1: iced 3 shot MOCHA
task-scheduler-1 prepared cold drink #2 for order #2: iced 3 shot MOCHA
task-scheduler-1 prepared cold drink #3 for order #3: iced 3 shot MOCHA
task-scheduler-1 prepared cold drink #4 for order #4: iced 3 shot MOCHA
task-scheduler-2 prepared hot drink #1 for order #1: hot 2 shot LATTE
task-scheduler-1 prepared cold drink #5 for order #5: iced 3 shot MOCHA
task-scheduler-1 prepared cold drink #6 for order #6: iced 3 shot MOCHA
task-scheduler-1 prepared cold drink #7 for order #7: iced 3 shot MOCHA
task-scheduler-1 prepared cold drink #8 for order #8: iced 3 shot MOCHA
task-scheduler-1 prepared cold drink #9 for order #9: iced 3 shot MOCHA
task-scheduler-2 prepared hot drink #2 for order #2: hot 2 shot LATTE
task-scheduler-1 prepared cold drink #10 for order #10: iced 3 shot MOCHA

task-scheduler-1 prepared cold drink #11 for order #11: iced 3 shot MOCHA
task-scheduler-2 prepared hot drink #3 for order #3: hot 2 shot LATTE
```

Please, consider to raise a StackOverflow question with much more details.
This is just impossible to help with so little information.
More over we don't handle question here on GitHub.

Thanks for understanding.
